// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbDMR.Models;

public partial class DMRContext : DbContext
{
    public DMRContext()
    {
    }

    public DMRContext(DbContextOptions<DMRContext> options)
        : base(options)
    {
    }





    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}