// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbCore.Models;

[Table("CoreUser")]
public partial class CoreUser
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string UserName { get; set; }

    [StringLength(200)]
    public string Person { get; set; }

    [Required]
    public string EncPassword { get; set; }

    public bool Disabled { get; set; }

    public bool IsAdmin { get; set; }

    public bool IsReset { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? loginedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime updatedAt { get; set; }

    [Required]
    [StringLength(100)]
    public string updatedBy { get; set; }

    public int level { get; set; }

    [StringLength(50)]
    public string post { get; set; }

    [StringLength(50)]
    public string Division { get; set; }

    [StringLength(50)]
    public string AdminScope { get; set; }

    [StringLength(250)]
    public string email { get; set; }
}